language: python
python:
  - "2.6"
#  - "3.3"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test-requirements.txt"
script:
  - "pep8 -r src/"
  - "python setup.py nosetests"
notifications:
  email: false
